### ISSUE TITLE
Windows (RailsInstaller): How to solve “certificate verify failed”

### ISSUE THREAD

**Issue by leesheppard** [reinteractive-open/installfest_guides#101]
Download [http://curl.haxx.se/ca/cacert.pem](http://curl.haxx.se/ca/cacert.pem) and save it into _c:\railsinstaller\cacert.pem_

Make sure you save it as a .pem file, rather than a text file.

1. Go to your _Computer > Advanced Settings > Environment Variables_

2. Create a new System Variable:

    **Variable**: SSL_CERT_FILE **Value**: C:\RailsInstaller\cacert.pem

3. Close all your command prompts, including your Rails server command prompt, etc.

4. Restart a new command prompt, gems should install or update without certificate failure.

Reference: [https://github.com/rubygems/rubygems/issues/704](https://github.com/rubygems/rubygems/issues/704)

**Comment by RachelleOnRails** [comment]
New guide will include updated Windows instructions that do not use Rails Installer
