### ISSUE TITLE
InvalidAuthenticityToken error after adding ajax support for creating comments

### ISSUE THREAD

**Issue by deepak-kapoor** [reinteractive-open/installfest_guides#18]
- Added code as per instructions on http://railsinstallfest.org/guides/installfest/finishing_a_basic_blog/ section AJAX commenting with unobtrusive JavaScript
 - Pushed changes to heroku http://powerful-tundra-7557.herokuapp.com/
 - Upon creating a new comment an InvalidAuthenticyToken error is returned. 

I have enabled dev errors on production to get more details.

**Comment by lengarvey** [comment]
Okay thanks. Closing this off until someone else has this sisue
