### ISSUE TITLE
Add content to remove <p id="notice"> duplicates

### ISSUE THREAD

**Issue by hackvan** [reinteractive-open/installfest_guides#242]
In this part of the [guide](https://github.com/reinteractive-open/installfest_guides/blob/develop/source/guides/installfest/adding_authentication.md):

Open `show.html.erb` and remove the line `<p id="notice"><%= notice %></p>`.

add `index.html.erb` too, that contain a duplicate `<p id="notice"><%= notice %></p>` tag.

**Comment by RachelleOnRails** [comment]
Thanks @hackvan, fixed.
