### ISSUE TITLE
Finish a Basic Blog - Bug in example code.

### ISSUE THREAD

**Issue by hackvan** [reinteractive-open/installfest_guides#244]
On this part of the [guide](https://github.com/reinteractive-open/installfest_guides/tree/master/source/guides/installfest/finishing_a_basic_blog.md)

the section:

_Open `app/controllers/comments_controller.rb` and change the create method to respond to AJAX requests as follows:_

```Ruby
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js { redirect_to @post }
    end
  end
```

we must remove the `{ redirect_to @post }` block's of `format.js`, because with this line Rails no process the `create.js.erb` file and not send via Ajax the comment created.

```Ruby
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end
```

**Comment by RachelleOnRails** [comment]
Thank you @hackvan, I have fixed the guide. Much appreciated.
