### ISSUE TITLE
Rails version on mavericks install guide

### ISSUE THREAD

**Issue by Chloef** [reinteractive-open/installfest_guides#46]
If you install multiple versions of Rails onto your computer you can choose which one to create an app with as follows:

rails _3.2.13_ new quick_blog
rails _4.0.1_ new quick_blog_4

This seems to confuse people, because they are typing EVERYTHING in the guide, instead of just the gem install rails -v 4.1.1

**Comment by RachelleOnRails** [comment]
Fixed.
