### ISSUE TITLE
Nitrous based development environment guide

### ISSUE THREAD

**Issue by ralovely** [reinteractive-open/installfest_guides#6]
Hi

I started looking into Nitrous from an InstallFest point of view.
I found a few small drawbacks but not enough, in my opinion, to not suggest it.
Mainly:
- I had a few lags on cmd-v # _needs more testing: my tests have been made on a cellular network. The rest was really responsive_
- No concept of localhost => cannot link ie.: localhost:3000/posts
- Heroku toolbelt is not the latest (2.39.5) # _Not sure it is a problem_
- we need to refresh the file browser manually when adding files via console # _Small UI inconvenience_

So, I started writing a Nitrous guide
I haven't PRed yet since it's not complete, it lives in my fork instead: https://github.com/ralovely/installfest_guides/tree/setup_nitrous/source/guides/installfest_4
Please, give me your feedback.
(We can also discuss it a bit at tonight's event)

A few notes:
- I have added an `assets` dir inside the guide, mainly for images.
  I think one dir per guide should be enough if we follow a name convention.
  Not sure this is how you intended it. It can be changed before merging.
- I created a page (mostly empty right now) explaining the various setups and their differences, linking to the actual guides for setting up. As we discussed, the first three could be **RailsInstaller**, **Vagrant** and **Nitrous**
- This will lead to small differences in the RoR guides at some points (dev URL, git, Heroku…).
  I imagine the differences could be colour coded, in small blockquotes. 
  If the number of setups stays around 3 this should be manageable.
- English is not my natural language, there are probably a ton of typos and weird phrase construction. Sorry about that.
- I placed it in the installfest_4 guide since Nitrous default env is with Rails 4.
- The CSS of the guides could use a `max-width:100%` for img.
- Nice design, I like the animation on the events date/rsvp ;)

**Comment by eppsmark** [comment]
This can be closed as https://www.nitrous.io/ discontinued the Nitrous Development Platform and Cloud IDE on November 14th, 2016.

**Comment by RachelleOnRails** [comment]
Good point, thanks @eppsmark
