### ISSUE TITLE
Error for creating file in guide: spec/features/managing_posts_spec.rb - Line 435

### ISSUE THREAD

**Issue by leesheppard** [reinteractive-open/installfest_guides#79]
Completed the guide on "Writing more Acceptance Tests" and creating file 'spec/features/managing_posts_spec.rb' encountered an error on Line 435 during test when it should have passed without error. Simple case issue with 'New post' causing the error during test, should be 'New Post'.

**Comment by RachelleOnRails** [comment]
That's awesome, thanks Lee. I have updated the guide with the correction. :-)
